services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aov_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      APP_URL: ${APP_URL}
      ASSET_URL: ${ASSET_URL}
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - aov

  webserver:
    image: nginx:stable-alpine
    container_name: aov_nginx
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - aov

  db:
    image: mysql:8.0
    container_name: aov_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "33062:3306"
    volumes:
      - aov_db_data:/var/lib/mysql
    networks:
      - aov

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: aov_pma
    restart: unless-stopped
    environment:
      PMA_HOST: db
    ports:
      - "8092:80"
    depends_on:
      - db
    networks:
      - aov

networks:
  aov:
    driver: bridge

volumes:
  aov_db_data:
